### ISSUE TITLE
Wrong attribute stored in session

### ISSUE THREAD

**Issue by ciaomario** [jgrams/webauthn_java_spring_demo#1]
AuthController.java method   @PostMapping("/registerauth") 

replace 

            session.setAttribute(userIdentity.getDisplayName(), registration);

by 

            session.setAttribute(userIdentity.getName(), registration);

in order to make it work

**Comment by pzygielo** [comment]
Thanks @ciaomario 

@jgrams - could this be fixed in repo, please?

**Comment by jgrams** [comment]
Fixed, thanks to @WakaWakaMan
